local nelt = require "..vendor.nelt.nelt"
local http = require "..vendor.http-nelua.http"
local layout = require ".layout-nelt"
local home = require ".components.home-nelt"
local function goals_content(tp: *nelt.Template, self: *http.Server)
tp:write([====[<h1>Goals</h1>]====])
end
local function content(tp: *nelt.Template, self: *http.Server)
home(tp, self, goals_content)
end
local function goals(tp: *nelt.Template, self: *http.Server)
layout(tp, "", content, self)
end
return goals
