local nelt = require "..vendor.nelt.nelt"
local http = require "..vendor.http-nelua.http"
local layout = require ".layout-nelt"
local home = require ".components.home-nelt"
local function profile_content(tp: *nelt.Template, self: *http.Server)
end
local function content(tp: *nelt.Template, self: *http.Server)
home(tp, self, "Profile", "", profile_content)
end
local function profile(tp: *nelt.Template, self: *http.Server)
layout(tp, "", content, self)
end
return profile
